# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
        exclude: ^\.devcontainer/devcontainer\.json$
      - id: check-toml
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
        types_or: [cuda, proto, textproto, python]
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
      additional_dependencies: [tomli]
      args: ["--toml", "pyproject.toml"]
      exclude: (?x)^(.*stemmer.*|.*stop_words.*|^CHANGELOG.md$|.*shakespeare.txt)
  - repo: local
    hooks:
      - id: add-license
        name: add-license
        entry: python tools/add_copyright.py
        language: python
        require_serial: true
      - id: mkinit
        name: mkinit
        entry: bash tools/generate_init_files.sh
        language: system
        files: (\.py$|^tools/generate_init_files\.sh$)
        pass_filenames: false
        args: []
      - id: generate-cli-docs
        name: generate-cli-docs
        entry: make generate-cli-docs
        language: python
        files: (\.py$|^tools/generate_cli_docs\.py$)
        pass_filenames: false
        args: []
      - id: generate-env-vars-docs
        name: generate-env-vars-docs
        entry: make generate-env-vars-docs
        language: python
        files: ^(src/aiperf/common/environment\.py|tools/generate_env_vars_docs\.py)$
        pass_filenames: false
        args: []
      - id: generate-plugin-artifacts
        name: generate-plugin-artifacts
        entry: make generate-all-plugin-files
        language: python
        files: (\.py$|^src/aiperf/plugin/(categories|plugins)\.yaml|src/aiperf/plugin/schema/schemas\.py|tools/generate_plugin_artifacts\.py)$
        pass_filenames: false
        args: []
      - id: validate-plugin-schemas
        name: validate-plugin-schemas
        entry: make validate-plugin-schemas
        language: python
        files: (\.py$|^src/aiperf/plugin/(categories|plugins)\.yaml|tools/validate_plugin_schemas\.py)$
        pass_filenames: false
        args: []
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]
